"""embed_web.py — bake web/ HTML source files into include/web_pages.h.

Replaces <link> / <script src> references to shared assets with their inlined
content so each page is a single self-contained HTML string served from flash.

Usage (standalone):
    python3 scripts/embed_web.py

Usage (PlatformIO pre-build):
    [env:esp32s3]
    extra_scripts = pre:scripts/embed_web.py
"""

import os
import re

# (source path relative to web/, C++ variable name)
PAGES = [
    ("index.html",              "WEB_PAGE_HOME"),
    ("config/general.html",     "WEB_PAGE_GENERAL"),
    ("config/connectivity.html", "WEB_PAGE_CONFIG_CONNECTIVITY"),
    ("config/wifi.html",        "WEB_PAGE_WIFI"),
    ("config/xbee.html",        "WEB_PAGE_XBEE"),
    ("config/audio.html",       "WEB_PAGE_AUDIO"),
    ("config/rc-radio.html",    "WEB_PAGE_RC_RADIO"),
    ("config/dome.html",            "WEB_PAGE_DOME"),
    ("config/serial-strings.html",  "WEB_PAGE_SERIAL_STRINGS"),
    ("config/gadgets.html",         "WEB_PAGE_GADGETS"),
    ("config/servos.html",          "WEB_PAGE_SERVOS"),
    ("config/pins.html",            "WEB_PAGE_PINS"),
    ("config/serial-ports.html",    "WEB_PAGE_SERIAL_PORTS"),
    ("config/controllers.html",     "WEB_PAGE_CONTROLLERS"),
    ("droid-control.html",             "WEB_PAGE_DROID_CONTROL"),
    ("safety.html",                 "WEB_PAGE_SAFETY"),
    ("monitor.html",                "WEB_PAGE_MONITOR"),
    ("update.html",                 "WEB_PAGE_UPDATE"),
    ("config/coming-soon.html",     "WEB_PAGE_COMING_SOON"),
    ("diagnostics.html",            "WEB_PAGE_DIAGNOSTICS"),
    ("troubleshooting.html",        "WEB_PAGE_TROUBLESHOOTING"),
]

_LINK_RE   = re.compile(r'[ \t]*<link rel="stylesheet" href="/assets/common\.css">\n?')
_SCRIPT_RE = re.compile(r'[ \t]*<script src="/assets/edit\.js"></script>\n?')

# Content-Security-Policy injected into every page.
# 'unsafe-inline' is required for <script> blocks and onclick= handlers.
# 'unsafe-eval' is intentionally absent — we don't use eval/new Function.
_CSP = ("default-src 'self'; "
        "script-src 'self' 'unsafe-inline'; "
        "style-src 'self' 'unsafe-inline'; "
        "connect-src 'self'")
_CSP_TAG = f'<meta http-equiv="Content-Security-Policy" content="{_CSP}">\n'

# Debug-mode indicator, injected into every page the same way as the CSP tag
# above (issue #199) -- a non-interactive corner badge, shown whenever
# /api/info reports debugmode on, so it's impossible to miss that a debug
# session is being written to the SD card regardless of which page someone
# is looking at. pointer-events:none so it never intercepts clicks on real
# controls underneath it (e.g. monitor.html's send bar sits at the bottom).
_DEBUG_BANNER_TAG = """<script>
(function(){
  function show(){
    if(document.getElementById('debugmode-badge'))return;
    var b=document.createElement('div');
    b.id='debugmode-badge';
    b.style.cssText='position:fixed;bottom:14px;right:14px;z-index:9999;'
      +'background:#8f2d3b;color:#fff;padding:.5rem .9rem;border-radius:6px;'
      +'font:600 10px/1.3 ui-monospace,"SF Mono",Menlo,monospace;letter-spacing:.08em;'
      +'box-shadow:0 2px 8px rgba(0,0,0,.35);pointer-events:none';
    b.textContent='\\u26a0 DEBUG MODE ACTIVE \\u2014 LOGGING TO SD';
    document.body.appendChild(b);
  }
  function check(){
    fetch('/api/info',{cache:'no-store'}).then(function(r){return r.ok?r.json():null;})
      .then(function(d){ if(d&&d.debugmode) show(); }).catch(function(){});
  }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',check);
  else check();
})();
</script>
"""


def run(project_dir: str) -> None:
    web_dir  = os.path.join(project_dir, "web")
    out_path = os.path.join(project_dir, "include", "web_pages.h")

    with open(os.path.join(web_dir, "assets", "common.css")) as f:
        css = f.read().strip()
    with open(os.path.join(web_dir, "assets", "edit.js")) as f:
        js = f.read().strip()

    out = [
        "// web_pages.h — GENERATED.  Edit sources in web/ then run scripts/embed_web.py.",
        "// Do not edit this file directly.",
        "#pragma once",
        "",
    ]

    for rel_path, var_name in PAGES:
        with open(os.path.join(web_dir, rel_path)) as f:
            html = f.read()

        html = _LINK_RE.sub(f"<style>\n{css}\n</style>\n", html)
        html = _SCRIPT_RE.sub(f"<script>\n{js}\n</script>\n", html)
        html = html.replace("<head>\n", f"<head>\n{_CSP_TAG}{_DEBUG_BANNER_TAG}", 1)

        if ')html"' in html:
            raise ValueError(f"{rel_path}: content contains ')html\"' which breaks the raw-string delimiter")

        out.append(f'static const char {var_name}[] = R"html({html})html";')
        out.append("")

    content = "\n".join(out)
    with open(out_path, "w") as f:
        f.write(content)

    rel = os.path.relpath(out_path, project_dir)
    print(f"[embed_web] {rel} regenerated from {len(PAGES)} pages in web/")


# PlatformIO extra_script entry point
try:
    Import("env")               # noqa: F821 — injected by SCons
    run(env.subst("$PROJECT_DIR"))
except NameError:
    # Standalone
    _here = os.path.dirname(os.path.abspath(__file__))
    run(os.path.dirname(_here))
